# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pete Marcano
email: pbmarcano91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The life of trial and error by a textbook millenial trying not to belong to
  any sort of group.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pbmarcano.com" # the base hostname & protocol for your site
twitter_username: pbmarcano
github_username:  pbmarcano


# Build settings
markdown: kramdown

# Additional gems
gems:
  - jekyll-seo-tag
